- hosts: load-balancers
  gather_facts: false
  become: true
  tasks:
  - name: install HAproxy
    package:
      name: haproxy
  - name: install configuration file
    template: 
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: start / enable HAPROXY
    service:
            name: haproxy
            enabled: true
            state: started
  - name: wait for Haproxy to be up on port 8080
    wait_for: 
      port: 8080
  - name: wait for Haproxy to be up on port 80
    wait_for:
      port: 80
  - name: ensure stat page return 200
    uri: 
      url: http://127.0.0.1:8080/
- hosts: app-servers
  gather_facts: false
  become: true
  tasks:
  - name: install tomcat
    package:
            name: tomcat8
  - name: start / enable tomcat
    service:
            name: tomcat8
            enabled: true
            state: started
  - name: wait for tomcat to be up on port 8080
    wait_for:
            port: 8080
  - name: ensure home page returns 200
    uri:
            url: http://127.0.0.1:8080/
            timeout: 240
